version: "3.8"

services:
  oracle-db-s6:
    image: container-registry.oracle.com/database/express:latest
    container_name: oracle-db-s6
    ports:
      - "1524:1521"
    environment:
      - ORACLE_PWD=contrasena
    volumes:
      - oracle_s6_data:/opt/oracle/oradata

volumes:
  oracle_s6_data:
