version: "3.8"

services:
  oracle-db-s5:
    image: container-registry.oracle.com/database/express:latest
    container_name: oracle-db-s5
    ports:
      - "1523:1521"
    environment:
      - ORACLE_PWD=contrasena
    volumes:
      - oracle_s5_data:/opt/oracle/oradata

volumes:
  oracle_s5_data:
