version: "3.8"

services:
  oracle-db-s3:
    image: container-registry.oracle.com/database/express:latest
    container_name: oracle-db-s3
    ports:
      - "1522:1521"
    environment:
      - ORACLE_PWD=contrasena
    volumes:
      - oracle_s3_data:/opt/oracle/oradata

volumes:
  oracle_s3_data:
